export const scopes = [
  'read_assigned_fulfillment_orders',
  'write_assigned_fulfillment_orders',
  'read_merchant_managed_fulfillment_orders',
  'write_merchant_managed_fulfillment_orders',
  'read_third_party_fulfillment_orders',
  'write_third_party_fulfillment_orders',
  // 'read_marketplace_fulfillment_orders',
  'read_cart_transforms',
  'write_cart_transforms',
  'read_checkout_branding_settings',
  'write_checkout_branding_settings',
  'read_content',
  'write_content',
  'read_online_store_pages',
  'read_customer_events',
  'write_pixels',
  'read_customer_merge',
  'write_customer_merge',
  // 'read_customer_payment_methods',
  'read_customers',
  'write_customers',
  'read_delivery_customizations',
  'write_delivery_customizations',
  'read_discounts',
  'write_discounts',
  'read_draft_orders',
  'write_draft_orders',
  'read_files',
  'write_files',
  'read_fulfillments',
  'write_fulfillments',
  'read_gift_cards',
  'write_gift_cards',
  'read_inventory',
  'write_inventory',
  'read_legal_policies',
  'read_locales',
  'write_locales',
  'read_locations',
  'write_locations',
  'read_markets',
  'write_markets',
  'read_marketing_events',
  'write_marketing_events',
  'read_metaobject_definitions',
  'write_metaobject_definitions',
  'read_metaobjects',
  'write_metaobjects',
  'read_online_store_navigation',
  'read_order_edits',
  'write_order_edits',
  'read_orders',
  'write_orders',
  // 'read_own_subscription_contracts',
  // 'write_own_subscription_contracts',
  // 'read_payment_gateways',
  // 'write_payment_gateways',
  // 'read_payment_mandate',
  // 'write_payment_mandate',
  'read_payment_terms',
  'write_payment_terms',
  'read_price_rules',
  'write_price_rules',
  'write_privacy_settings',
  'read_privacy_settings',
  'read_products',
  'write_products',
  'read_purchase_options',
  'write_purchase_options',
  'read_returns',
  'write_returns',
  'read_script_tags',
  'write_script_tags',
  'read_shipping',
  'write_shipping',
  'read_store_credit_account_transactions',
  'write_store_credit_account_transactions',
  'read_themes',
  'write_themes',
  'read_validations',
  'write_validations',
];
