services:
  example_client:
    container_name: example_client
    image: node-typescript
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_HOST=example_client
      - PORT=80
    env_file: .env
    ports:
      - "3001:80"
    volumes:
      # - .:/app
      - ./src:/app/src
      - ./exampleClient:/app/exampleClient
      - ./__tests__:/app/__tests__
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: null
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: shopify
    ports:
      - "54321:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  mongo-data:
  postgres-data:

