services:
  example_client:
    environment:
      - CLIENT_ID=<CLIENT_ID>
      - CLIENT_SECRET=<CLIENT_SECRET>
      - SHOPIFY_AUTH_ENDPOINT=<SHOPIFY_AUTH_ENDPOINT>
      - MONGODB_URI=mongodb://root:example@mongo:27017/
    volumes: []
    env_file: []
  mongo:
    extends:
      file: docker-compose.yml
      service: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
