services:
  example_client:
    container_name: example_client
    image: node-typescript
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_HOST=example_client
      - PORT=80
      - CLIENT_ID=<CLIENT_ID>
      - CLIENT_SECRET=<CLIENT_SECRET>
      - SHOPIFY_AUTH_ENDPOINT=<SHOPIFY_AUTH_ENDPOINT>
      - MONGODB_URI=mongodb://root:example@mongo:27017/
    ports:
      - "3001:80"
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local
