services:
  shopify_auth:
    container_name: shopify_auth
    image: node-typescript
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_HOST=shopify_auth
      - PORT=80
    ports:
      - "3000:80"
    volumes:
      # - .:/app
      - ./src:/app/src
      - ./__tests__:/app/__tests__
