services:
  shopify_auth:
    entrypoint: ["npm", "run", "dev"]
    extends: 
      file: docker-compose.yml
      service: shopify_auth
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      HOSTNAME: ${HOSTNAME}
    env_file: ".env"